# Generated by Django 5.2.4 on 2025-09-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quote',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.TextField(unique=True, verbose_name='Текст цитаты'),
        ),
    ]
