# Generated by Django 5.2.4 on 2025-09-05 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_alter_quote_unique_together_alter_quote_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='year',
        ),
    ]
